---
name: ALN File Merge

on:
  workflow_dispatch:  # Enables manual trigger

jobs:
  process_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pandas

      - name: Merge, Clean, and Standardize CSV Files
        run: |
          python -c "
          import os
          import pandas as pd
          from datetime import datetime
          import glob

          folder = './backend/schemas/source/data/ALNs_raw_downloads'
          timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
          output_file = f'./backend/schemas/source/data/cfda-lookup-{timestamp}.csv'
          invalid_file = f'./backend/schemas/source/data/invalid-program-numbers-{timestamp}.csv'

          print(f'Looking for CSV files in: {folder}')
          csv_files = glob.glob(f'{folder}/*.csv')
          print(f'CSV files found: {csv_files}')

          if not csv_files:
              print('No data found in the input files.')
              exit(1)

          all_data = []
          for f in csv_files:
              try:
                  df = pd.read_csv(f, encoding='utf-8')
              except UnicodeDecodeError:
                  print(f'Warning: Could not read {f} with UTF-8. Trying ISO-8859-1.')
                  df = pd.read_csv(f, encoding='ISO-8859-1')
              all_data.append(df)

          combined_data = pd.concat(all_data, ignore_index=True)

          # Clean and validate the Program Number column
          if 'Program Number' in combined_data.columns:
              combined_data['Program Number'] = combined_data['Program Number'].apply(
                  lambda x: str(x).strip() if pd.notnull(x) else None
              )
              # Separate valid and invalid rows
              valid_rows = combined_data['Program Number'].str.contains(r'\.', na=False)
              valid_data = combined_data[valid_rows]
              invalid_data = combined_data[~valid_rows]
              print(f'Filtered invalid Program Numbers. Remaining rows: {len(valid_data)}')

              # Save invalid rows for debugging
              if not invalid_data.empty:
                  invalid_data.to_csv(invalid_file, index=False, encoding='utf-8')
                  print(f'Saved invalid rows to: {invalid_file}')
          else:
              print('Warning: Program Number column not found. Skipping validation.')
              valid_data = combined_data

          # Standardize the column order and fill missing values
          all_columns = valid_data.columns.unique()
          standardized_data = valid_data.reindex(columns=all_columns, fill_value=None)

          column_mapping = {
              'Title': 'Program Title',
              'Assistance Listings Number': 'Program Number',
              'Date Published': 'Date Published',
              'Department/Ind. Agency': 'Department/Ind. Agency',
              'Funded': 'Funded',
              'Last Date Modified': 'Last Date Modified',
              'POC Information': 'POC Information',
              'Related Federal Assistance': 'Related Federal Assistance',
              'Sub-Tier': 'Sub-Tier',
              'Types of Assistance': 'Types of Assistance'
          }

          standardized_data = standardized_data.rename(columns=column_mapping)
          print(f'Saving merged and standardized CSV to: {output_file}')
          standardized_data.to_csv(output_file, index=False, encoding='utf-8')
          print('CSV processing completed successfully.')
          "

      - name: Commit and Push Merged File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./backend/schemas/source/data/cfda-lookup-*.csv
          git add ./backend/schemas/source/data/invalid-program-numbers-*.csv
          git diff --cached --quiet || git commit -m "Add cleaned and validated CSV file with invalid rows logged"
          git push

      - name: Run Make All
        run: make -C backend/schemas all
