---
name: Test Read CSV File

on:
  workflow_dispatch:  # Enables manual trigger

jobs:
  test_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files in the Target Folder
        run: |
          echo "Files in the target folder:"
          ls "./backend/schemas/source/data/ALN raw downloads for CFDA lookup files"

      - name: Read and Print First Line of a CSV
        run: |
          # Locate the folder and find a CSV file
          TARGET_FOLDER="./backend/schemas/source/data/ALN raw downloads for CFDA lookup files"
          CSV_FILE=$(ls $TARGET_FOLDER/*.csv | head -n 1)

          if [ -z "$CSV_FILE" ]; then
            echo "No CSV files found in $TARGET_FOLDER"
            exit 1
          fi

          echo "Reading first line of: $CSV_FILE"
          head -n 1 "$CSV_FILE"
